### ISSUE TITLE
Error: could not get uid/gid

### ISSUE THREAD

**Issue by Laurian** [npm/uid-number#3]
This error was initially reported here: https://github.com/npm/npm/issues/4719

I compiled and installed node 0.10.26 on Ubuntu 12.04; npm update dies:

```
root@dev:/opt/node-v0.10.26# npm update -g
npm ERR! Error: could not get uid/gid
npm ERR! [ 'nobody', 0 ]
npm ERR! 
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/uid-number/uid-number.js:36:24
npm ERR!     at ChildProcess.exithandler (child_process.js:635:7)
npm ERR!     at ChildProcess.EventEmitter.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:743:16)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:810:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.2.0-54-virtual
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "update" "-g"
npm ERR! cwd /opt/node-v0.10.26
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/node-v0.10.26/npm-debug.log
npm ERR! not ok code 0
```

Trying as non root a `sudo npm update -g` yields the same error, only difference is `[ 'nobody', 1000 ]` instead of `[ 'nobody', 0 ]`

The only way I could quickly get around was to comment out the error check (line 36), which I guess is not the proper way to do it.

**Comment by lesion** [comment]
I'm reopening this 'cause I've the same error (for different reasons).
I'm trying to run node/npm inside a `runc` container. I've tried compiled node (7.5.0) and two packaged release (6.9.5 and 7.2.1) and all of them exit with a bad segfault when trying to install any package globally with `npm install -g <package>`

npm output:
```
Error: could not get uid/gid
[ 'nobody', 0 ]
    at /usr/lib/node_modules/npm/node_modules/uid-number/uid-number.js:37:16
```
looking at that, I saw an `exec_file` to `./get-uid-gid.js`, that's the results of running it manually:
```
# node /usr/lib/node_modules/npm/node_modules/uid-number/get-uid-gid.js  nobody 0
[ 'nobody', 0 ]
Segmentation fault
```

and here last lines of strace:
```
write(11, "[ 'nobody', 0 ]\n", 16[ 'nobody', 0 ]
)      = 16
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1 RT_2], [], 8) = 0
rt_sigprocmask(SIG_BLOCK, ~[], NULL, 8) = 0
rt_sigaction(SIGRT_2, {0x5572dab598, ~[], SA_RESTORER, 0x5572db2a44}, NULL, 8) = 0
getpid()                                = 16651
gettid()                                = 16651
openat(AT_FDCWD, "/proc/self/task", O_RDONLY|O_LARGEFILE|O_DIRECTORY|O_CLOEXEC) = 12
fcntl(12, F_SETFD, FD_CLOEXEC)          = 0
kill(16651, SIGRT_2)                    = ? <unavailable>
+++ killed by SIGSEGV +++
Segmentation fault
```

ps. don't know if this is the right place for this
pps. this is an `arm64`

**Comment by skl** [comment]
@lesion Same when running a raspian docker container through qemu-user-static (so emulating an armv7l machine). I worked around this by hard-coding for my target user (root) inside the container:

```
echo "module.exports = function uidNumber(uid, gid, cb) {cb(null, 0, 0)}" > /usr/lib/node_modules/npm/node_modules/uid-number/uid-number.js
```

Maybe `uid-number` package could parse output of `id <username>` and `getent group <groupname>` commands to do the lookups instead of JS.

**Comment by mathias-luedtke** [comment]
@skl: I have the same use case, `npm config set unsafe-perm true` worked for me

**Comment by vielmetti** [comment]
Same, building Mastodon in Docker, I used the `npm config set unsafe-perm true` line in the Dockerfile and was able to make it past the issue. 

http://github.com/tootsuite/mastodon/issues/802

**Comment by raulgomis** [comment]
We are still experiencing these errors in node alpine for M5 instances in AWS.

`docker container  run  -it node:8-alpine /bin/sh -c 'npm -g --verbose'`

```
Error: could not get uid/gid
[ 'nobody', 0 ]

    at /usr/local/lib/node_modules/npm/node_modules/uid-number/uid-number.js:37:16
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
TypeError: Cannot read property 'get' of undefined
    at errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:83:20
    at cb (/usr/local/lib/node_modules/npm/lib/npm.js:224:22)
    at /usr/local/lib/node_modules/npm/lib/npm.js:262:24
    at /usr/local/lib/node_modules/npm/lib/config/core.js:81:7
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/npm/lib/config/core.js:80:13
    at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at afterExtras (/usr/local/lib/node_modules/npm/lib/config/core.js:178:20)
    at Conf.<anonymous> (/usr/local/lib/node_modules/npm/lib/config/core.js:236:22)
    at /usr/local/lib/node_modules/npm/node_modules/uid-number/uid-number.js:39:14
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:205
  if (npm.config.get('json')) {
                 ^

TypeError: Cannot read property 'get' of undefined
    at process.errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:378:26)
```

**Comment by shavo007** [comment]
i got this issue moving from docker image mhart/alpine-node:10.6.0 to mhart/alpine-node:10.7.0

**Comment by raulgomis** [comment]
@isaacs any comments on this issue? are you guys planning to investigate this issue?

@shavo007 both of your images fail in a EC2 M5 instance. Details here:

`docker container run -it mhart/alpine-node:10.6.0 /bin/sh -c 'npm -g --verbose'`
```
Unable to find image 'mhart/alpine-node:10.6.0' locally
10.6.0: Pulling from mhart/alpine-node
ff3a5c916c92: Pull complete 
96bc206ec963: Pull complete 
Digest: sha256:607a6e1e75ca22a5aa090e055a86c35bf59823f5d8c5633613c61166526315df
Status: Downloaded newer image for mhart/alpine-node:10.6.0
Error: could not get uid/gid
[ 'nobody', 0 ]

    at /usr/lib/node_modules/npm/node_modules/uid-number/uid-number.js:37:16
    at ChildProcess.exithandler (child_process.js:298:5)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
TypeError: Cannot read property 'get' of undefined
    at errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at /usr/lib/node_modules/npm/bin/npm-cli.js:76:20
    at cb (/usr/lib/node_modules/npm/lib/npm.js:228:22)
    at /usr/lib/node_modules/npm/lib/npm.js:266:24
    at /usr/lib/node_modules/npm/lib/config/core.js:83:7
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/npm/lib/config/core.js:82:13
    at f (/usr/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at afterExtras (/usr/lib/node_modules/npm/lib/config/core.js:173:20)
    at Conf.<anonymous> (/usr/lib/node_modules/npm/lib/config/core.js:231:22)
/usr/lib/node_modules/npm/lib/utils/error-handler.js:205
  if (npm.config.get('json')) {
                 ^

TypeError: Cannot read property 'get' of undefined
    at process.errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at process.emit (events.js:182:13)
    at process._fatalException (internal/bootstrap/node.js:437:27)
```


`docker container run -it mhart/alpine-node:10.7.0 /bin/sh -c 'npm -g --verbose'`
```
Unable to find image 'mhart/alpine-node:10.7.0' locally
10.7.0: Pulling from mhart/alpine-node
911c6d0c7995: Pull complete 
8409151da7fb: Pull complete 
Digest: sha256:fc5dfe8af093948a8f48b018db5addae767c383c8d3430bcd131e371406bfde5
Status: Downloaded newer image for mhart/alpine-node:10.7.0
Error: could not get uid/gid
[ 'nobody', 0 ]

    at /usr/lib/node_modules/npm/node_modules/uid-number/uid-number.js:37:16
    at ChildProcess.exithandler (child_process.js:298:5)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:599:12)
TypeError: Cannot read property 'get' of undefined
    at errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at /usr/lib/node_modules/npm/bin/npm-cli.js:76:20
    at cb (/usr/lib/node_modules/npm/lib/npm.js:228:22)
    at /usr/lib/node_modules/npm/lib/npm.js:266:24
    at /usr/lib/node_modules/npm/lib/config/core.js:83:7
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/npm/lib/config/core.js:82:13
    at f (/usr/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at afterExtras (/usr/lib/node_modules/npm/lib/config/core.js:173:20)
    at Conf.<anonymous> (/usr/lib/node_modules/npm/lib/config/core.js:231:22)
/usr/lib/node_modules/npm/lib/utils/error-handler.js:205
  if (npm.config.get('json')) {
                 ^

TypeError: Cannot read property 'get' of undefined
    at process.errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at process.emit (events.js:182:13)
    at process._fatalException (internal/bootstrap/node.js:472:27)

```

**Comment by shavo007** [comment]
Interesting @raulgomis. I rolled back my version on a build agent and it worked...

**Comment by jhnlsn** [comment]
Watching this issue.  have same problem

**Comment by nshtg** [comment]
How can such a high severity bug **STILL NOT BE FIXED** on **LTS**??

**Comment by pranasziaukas** [comment]
Experiencing this behaviour in an official Docker container `node:alpine`.

**Comment by Gp2mv3** [comment]
We also have the issue when building with Gitlab CI. :confused:

**Comment by GauSim** [comment]
also have that issue in `node:8.10.0-alpine` on CI :/

**Comment by garrett-vangilder** [comment]
Was able to fix this issue by updating node alpine to 10.3.0 and adding 
`npm config set unsafe-perm true` unsure if this is the right approach.

**Comment by T0T4R4** [comment]
@garrett-vangilder  probably not but yep it works ! so... I'll throw a "meh" at security... I haven't peer-reviewed the 1750 npm packages anyway, so... we live in a Time where risk is everywhere... if i get hacked i'll flee to Fidji !

**Comment by underyx** [comment]
@isaacs could you reopen this please? we're seeing the same exact problem on M5 instances as reported above

**Comment by naureen-34** [comment]
Any solution for it yet? Facing the same issue with node:8.10.0-alpine on bitbucket pipeline.
Versions in use:
npm v5.3.0
node v8.4.0
yarn  v1.9.4

**Comment by dysinger** [comment]
A 4 year old issue marked "closed" that still has super active comments. LOL. I love node.js

This still happens on both LTS 8.x and current 10.x on both armhf and aarch64 (arm 32 & 64 bit)

**Comment by sseide** [comment]
same for me - running inside docker container base on "alpine:3.7" with alpine provided packages of node / node-npm within gitlab runner pipeline:

---- Node / NPM versions -------------------------------------
node v8.9.3
npm 5.5.1

```
Error: could not get uid/gid
[ 'nobody', 0 ]

    at /usr/lib/node_modules/npm/node_modules/uid-number/uid-number.js:37:16
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
TypeError: Cannot read property 'get' of undefined
    at errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at /usr/lib/node_modules/npm/bin/npm-cli.js:83:20
    at cb (/usr/lib/node_modules/npm/lib/npm.js:214:22)
    at /usr/lib/node_modules/npm/lib/npm.js:252:24
    at /usr/lib/node_modules/npm/lib/config/core.js:81:7
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/npm/lib/config/core.js:80:13
    at f (/usr/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at afterExtras (/usr/lib/node_modules/npm/lib/config/core.js:178:20)
    at Conf.<anonymous> (/usr/lib/node_modules/npm/lib/config/core.js:237:22)
/usr/lib/node_modules/npm/lib/utils/error-handler.js:205
  if (npm.config.get('json')) {
                 ^

TypeError: Cannot read property 'get' of undefined
    at process.errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:374:26)
```

**Comment by tanmaiaccion** [comment]
Same issue here: node version: 8.9.3

npm WARN using --force I sure hope you know what you are doing.
Error: could not get uid/gid
[ 'nobody', 0 ]

    at /usr/lib/node_modules/npm/node_modules/uid-number/uid-number.js:37:16
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
TypeError: Cannot read property 'get' of undefined
    at errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at /usr/lib/node_modules/npm/bin/npm-cli.js:83:20
    at cb (/usr/lib/node_modules/npm/lib/npm.js:214:22)
    at /usr/lib/node_modules/npm/lib/npm.js:252:24
    at /usr/lib/node_modules/npm/lib/config/core.js:81:7
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/npm/lib/config/core.js:80:13
    at f (/usr/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at afterExtras (/usr/lib/node_modules/npm/lib/config/core.js:178:20)
    at Conf.<anonymous> (/usr/lib/node_modules/npm/lib/config/core.js:237:22)
/usr/lib/node_modules/npm/lib/utils/error-handler.js:205
  if (npm.config.get('json')) {
                 ^

TypeError: Cannot read property 'get' of undefined
    at process.errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:374:26)

**Comment by giannidhooge** [comment]
+1 on `node:9.4-alpine`

**Comment by dysinger** [comment]
@isaacs can we reopen this issue?

**Comment by ghost** [comment]
Also a problem on`frolvlad/alpine-glibc` which is based on `alpine:3.8`.

**Comment by lpil** [comment]
Could you link the issue please @mxhllnn ?

Can we get this issue reopened please @isaacs ?

**Comment by ghost** [comment]
@lpil sorry, what I wrote was misleading. I just meant "+1 for frolvlad/alpine-glibc ".

**Comment by cristin** [comment]
Also an issue on Bitbucket pipeline and node alpine 8.11.3

**Comment by ahmadnassri** [comment]
seeing the same issue on cricle with `node:alpine` (`node:10-alpine`)

**Comment by ghost** [comment]
same issue arm32v7/node:carbon-stretch.  thanks @ipa-mdl

**Comment by bgroupe** [comment]
same issue with jenkins-only and node:6.11.2-alpine

**Comment by poupryc** [comment]
same issue with `arm64v8/node:10-alpine`

**Comment by yottachen** [comment]
Same issue with node:8-alpine

**Comment by evisong** [comment]
Same issue (`npm install -g` causes `Error: could not get uid/gid [ 'nobody', 0 ]`) when running with node:8-alpine on an AWS EC2 instance.

**Comment by CapMousse** [comment]
Same here with `nginx:alpine` on an EC2 instance

**Comment by rodmaz** [comment]
Same here `nginx:alpine` on EC2 instance.

**Comment by rodmaz** [comment]
This solves the permission problem: 
`sudo npm config set unsafe-perm true`

See this [thread](https://github.com/npm/npm/issues/4719) explains.

**Comment by sseide** [comment]
Same problem on alpine:3.8 with NodeJS v8.11.4 / NPM 5.6.0 running a root. The journey continues...

@rodmaz - this is a workaround and no sollution. This package an/or npm just needs to be fixed.
And please do not advocate setting this parameter GLOBALLY for all npm operations. If there is a problem installing a specific software / on a specific system this should be set as command line param or environment variable for this call only!
`npm install -g --unsafe-perm blah` or `NPM_CONFIG_UNSAFE_PERM=true npm install -g foo`

**Comment by poupryc** [comment]
No maintainer reopens this issue for such a critical problem?

**Comment by vukor** [comment]
Same issue with alpine:latest

**Comment by robbyemmert** [comment]
I've opened a fresh issue to add visibility: https://github.com/npm/uid-number/issues/7

**Comment by SadPencil** [comment]
Same issue with alpine:latest, on arm64

**Comment by gabrie30** [comment]
Also happening with node:8-alpine

**Comment by rudimk** [comment]
Facing this on node:8-alpine. Interestingly enough, it cropped up a few months ago in one particular npm project, and adding `RUN npm config set unsafe-perm true` to the Dockerfile solved it. It suddenly happened with another project today, so I'm not sure what the real problem is here.

**Comment by BlueSeph28** [comment]
Confirmed Using node:10.15.0-alpine in the Dockerfile, with an Amazon EC2, there is the UID error.
Adding **RUN npm config set unsafe-perm true** solved it.

**Comment by jmcvetta** [comment]
Notice the word "unsafe" in the workaround under discussion.  Gives me the creeps.  So I prefer something like this:

```
RUN npm config set unsafe-perm true \
    && npm install some_package \
    && npm config set unsafe-perm false
```

That way we allow the unsafe operation where we really need it, then go back to normal sane mode.

**Comment by rudimk** [comment]
> Notice the word "unsafe" in the workaround under discussion. Gives me the creeps. So I prefer something like this:
> 
> ```
> RUN npm config set unsafe-perm true \
>     && npm install some_package \
>     && npm config set unsafe-perm false
> ```
> That way we allow the unsafe operation where we really need it, then go back to normal sane mode.

Damn and blast, didn't think of that. Going to push this out right away. Thanks!

**Comment by SadPencil** [comment]
After all, `npm config set unsafe-perm true` is just a workaround.
A **solution** is needed, not a **workaround**.

**Comment by rudimk** [comment]
At the risk of sounding whiny, I have to say I'm a little taken aback at
the fact that no solution exists. The fact that there's no predictable
pattern to its occurrence is all the more worrying.

I understand that open source is used at one's own risk, and expecting
fixes when I'm not contributing to the financial maintenance of npm is not
okay - but at the same time, I can't help but question the investments I've
made with the node.js ecosystem and npm in terms of time and effort.

**Comment by levindoneto** [comment]
For me, the workaround worked, but it doesn't seem to be a very reliable solution tbh...

**Comment by lukepighetti** [comment]
Same issue on `node:10-alpine`

**Comment by danieldram** [comment]
This issue just happened to me as well on npm install -g nodemon with this image. ```node:8-alpine```

**Comment by orende** [comment]
Not sure why this issue hasn't been addressed yet after 4 years. Is this just a spare-time hobby project for NPM or something?

**Comment by lpil** [comment]
@orende Probably best to reply in this issue https://github.com/npm/uid-number/issues/7

**Comment by keblodev** [comment]
not sure how why was it closed and not reopened again after so much time :\
faced this today on `node:8.4.0-alpine`

**Comment by thorsten** [comment]
Same here, ran into this issue with node:10-alpine and node:11-alpine. Got it fixed with the "workaround" above.

**Comment by ThomasGHenry** [comment]
Still seeing this.

**Comment by neutraali** [comment]
> Still seeing this.

Can confirm - Our `node:10-alpine` docker images for CI have started failing their pipelines with:
```
Error: could not get uid/gid [ 'nobody', 0 ]
    at /usr/local/lib/node_modules/npm/node_modules/uid-number/uid-number.js:37:16
    at ChildProcess.exithandler (child_process.js:298:5)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:5)
TypeError: Cannot read property 'get' of undefined
    at errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:76:20
    at cb (/usr/local/lib/node_modules/npm/lib/npm.js:228:22)
    at /usr/local/lib/node_modules/npm/lib/npm.js:266:24
    at /usr/local/lib/node_modules/npm/lib/config/core.js:83:7
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/npm/lib/config/core.js:82:13
    at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:25:25)
    at afterExtras (/usr/local/lib/node_modules/npm/lib/config/core.js:173:20)
    at Conf.<anonymous> (/usr/local/lib/node_modules/npm/lib/config/core.js:231:22)

/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:205
  if (npm.config.get('json')) {
                 ^
TypeError: Cannot read property 'get' of undefined
    at process.errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at process.emit (events.js:182:13)
    at process._fatalException (internal/bootstrap/node.js:437:27)
```

**Comment by isaacs** [comment]
This issue is 5 years old.

Unless you haven't updated your systems since 2014, whatever you're seeing, it's not "the same" issue, even if it's similar error message text.

I know it's easier to just post a new comment on an existing thread.  But I need you to create a new issue.  Please include the version of npm that you are using, any debug log file that was generated, and the command that you're running.

Thanks.
