### ISSUE TITLE
Unknown signal 33

### ISSUE THREAD

**Issue by thom-nic** [npm/uid-number#6]
I'm installing nodejs and npm@4.2.0 inside a chroot for an armhf debootstrap.  When I do `npm i -g npm@4.2.0` something inside uid-number dies with the following:

```
# npm update -g --verbose
SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at /usr/lib/node_modules/npm/node_modules/uid-number/uid-number.js:43:18
    at ChildProcess.exithandler (child_process.js:197:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
```

I dug a little deeper and when I run get-uid-gid.js:
```
# node /usr/lib/node_modules/npm/node_modules/uid-number/get-uid-gid.js
[ 0, 0 ]
Unknown signal 33
```

version info:
```
# node --version
v6.9.5
# npm --version
3.10.10
```

This is preventing me from doing `npm i -g` for anything inside the chroot.

**Comment by knoxcard** [comment]
@thom-nic - looks like you solved this issue.

https://github.com/nodejs/node/issues/12537

"Hey Ben just wanted to say thanks a ton for guiding me to a solution even though it was not an issue with node! ❤️ Much appreciated."





Close ticket?
